# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image_processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_processing.proto\x12\x10image_processing\"\x97\x01\n\x0eProcessRequest\x12\x10\n\x08image_id\x18\x01 \x01(\x05\x12\x12\n\nimage_path\x18\x02 \x01(\t\x12\x39\n\x0ftransformations\x18\x03 \x03(\x0b\x32 .image_processing.Transformation\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\"M\n\x0eTransformation\x12\x19\n\x11transformation_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\"~\n\x0fProcessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_path\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x05\x12\x12\n\nimage_data\x18\x05 \x01(\x0c\" \n\rStatusRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"I\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\x12\x14\n\x0cmemory_usage\x18\x03 \x01(\x02\x32\xbd\x01\n\x0eImageProcessor\x12U\n\x0cProcessImage\x12 .image_processing.ProcessRequest\x1a!.image_processing.ProcessResponse\"\x00\x12T\n\rGetNodeStatus\x12\x1f.image_processing.StatusRequest\x1a .image_processing.StatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSREQUEST']._serialized_start=45
  _globals['_PROCESSREQUEST']._serialized_end=196
  _globals['_TRANSFORMATION']._serialized_start=198
  _globals['_TRANSFORMATION']._serialized_end=275
  _globals['_PROCESSRESPONSE']._serialized_start=277
  _globals['_PROCESSRESPONSE']._serialized_end=403
  _globals['_STATUSREQUEST']._serialized_start=405
  _globals['_STATUSREQUEST']._serialized_end=437
  _globals['_STATUSRESPONSE']._serialized_start=439
  _globals['_STATUSRESPONSE']._serialized_end=512
  _globals['_IMAGEPROCESSOR']._serialized_start=515
  _globals['_IMAGEPROCESSOR']._serialized_end=704
# @@protoc_insertion_point(module_scope)
